### ISSUE TITLE
Memory limitation

### ISSUE THREAD

**Issue by tympanix** [hauke96/tiny-http-proxy#1]
I wanted to try something similar and came across your repo. I think the line here is quite troublesome:
https://github.com/hauke96/tiny-http-proxy/blob/89ff15736ecef2e0ca13216d1d5180bd817fd19b/main.go#L85

Having everything stored in memory before caching it is a bad approach. Any ideas?

**Comment by hauke96** [comment]
That's true, this is a time bomb to be honest :/

The solution would probably to use `io.Copy(src, dest)` to copy the data into the cache-file as this uses a 32K large buffer. In order to implement this, I would create a new `put` function in the `cache.go` which takes a reader instead of the `content []byte` to write the readers content to disk.

You can implement this fix if you wan't. Currently I don't have that much time, so it'll probably take a while until I can work on this. Just let me know if you want to work in this :)

**Comment by tympanix** [comment]
That's cool. I actually has the exact same implementation in mind.

I can't seem to find a small robust caching proxy anywhere. I tried Squid and Nginx ofc., but it bottlenecks at ~30MB/s even on a cache hit and 100% cpu usage. Maybe my hardware is slow (laptop), and yes, maybe the configuration is suboptimal. However, I get 10x that speed with 200 lines of go, take your proxy for example, which seems unfair. A proxy like this is not a bad idea.

I can probably hack something together when I have time.

Sorry for the rant 🤷‍♂️

**Comment by hauke96** [comment]
This is a real problem right now, so I'm glad you found this bug. I would also love to see your hacking as a pull request, so feel free to hack something together :)

**Comment by tympanix** [comment]
Ouch, I forgot to read some code and I realised every item is cached in memory even when they are served once. A simple `io.Copy` would not go a long way. Best would be to drop in memory caching completely until we have some configuration/requirements in place; total max memory constraint, replacement strategy (e.g. LFU), max object size in memory etc. This is a mouthful.

**Comment by hauke96** [comment]
That's correct, everything currently is in-memory and yes, a proper cache solution would be great.

A LFU cache would certainly be a good choice. There might be better ones like an ARC or so but I think a LRU/LFU kind of cache is just fine. 

This is more complex than just fixing the bug you reported and also a whole new topic, so I think this is stuff for a new issue (s. #2 ).

**Comment by hauke96** [comment]
Fixed the memory issue.

Tested it with >300MB large files and the memory consumption was steady at a few KB. The fix required more code changes than I expected, because for instance a `io.reader` only allows to be read once. We need two times: first copy it into a file/the on-memory cache and then copy the data a second time to the HTTP response writer.

So when we have a cache miss, the data is first written to disk (or when under a certain configurable size, it's also written to the in-memory cache as well) and then read from cache and written to the response. Yes, large amount of data are written and directly read from disk but I don't know of a better solution the the "only read once from a reader" situation. And at least locally it was pretty fast.

**Comment by tympanix** [comment]
That's amazing!

I don't think in general there is an issue serving large files from disk. However, I do agree that waiting for a large file to be cached completely to disk before it is served to the client is not ideal. One quick trick that comes to mind is the `io.TeeReader` which could then write to disk, as the content is read from the http response. However, what if multiple clients asks for the same file while it is in the process of being cached? There are a lot of scenarios to account for. Probably a discussion for another time.

Great work 👍

**Comment by hauke96** [comment]
Thanks :) I first tried the TeeReader but ended up with the same memory issue as before. I don't know how that reader exactly works but I think it has to put the whole data into memory in order to be readable multiple times. Maybe that reader works better when used concurrently? I don't know...

The whole access control could definitely be tweaked and yeah, that's a new future topic :D
